# Generated by Django 5.2.8 on 2026-03-13 12:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='内容'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
