# Generated by Django 5.2.8 on 2026-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_name_alter_project_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='项目详述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='是否已完结'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='项目展示链接'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(blank=True, null=True, verbose_name='源码链接'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='开始时间'),
        ),
    ]
