# Generated by Django 5.2.8 on 2026-01-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_description_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
